[WIP] StandardJS
danschultzer/blazing-bookkeeper-server pull request #8
Opened 2016-11-29 04:36 UTC by Schultzer

2016-11-29 07:37 UTC, danschultzer requested changes

2016-11-29 07:37 UTC, danschultzer commented on config/config.js
> +  var nodeEnv = process.env.NODE_ENV || 'production'
Just move this down to the next line instead

2016-11-29 07:37 UTC, danschultzer commented on controllers/api_breakpad.js
> +    var writeStream
Why not just do `var writeStream = gfs. ...`?

2016-11-29 07:37 UTC, danschultzer commented on controllers/api_breakpad.js
> +      if (error) {
Probably nicer as a one-liner?

2016-11-29 07:37 UTC, danschultzer commented on controllers/api_breakpad.js
> +      if (error) {
(This also is relevant to all subsequent identical code)

2016-11-29 07:37 UTC, danschultzer commented on controllers/api_receipt.js
> +  var storage
Why not just do `var storage = ...`?

2016-11-29 07:37 UTC, danschultzer commented on controllers/api_receipt.js
> +    console.log(req.file.path)
Should be removed, it's debug code.

2016-11-29 07:37 UTC, danschultzer commented on controllers/auth_github.js
> +    var User
This doesn't make any sense?

2016-11-29 07:37 UTC, danschultzer commented on models/admin.js
> +  if (!this.created_at) {
Maybe one-liner?

2016-11-29 07:37 UTC, danschultzer commented on models/bug_report.js
> +  if (!this.created_at) {
Maybe one-liner?

2016-11-29 07:37 UTC, danschultzer commented on models/crash_report.js
> +  if (!this.created_at) {
Maybe one-liner?

2016-11-29 07:37 UTC, danschultzer commented on public/javascripts/receipt.js
> +      var location
Why this?

2016-11-29 08:03 UTC, Schultzer commented on models/admin.js
> +  if (!this.created_at) {
Then we not following StandardJS

2016-11-29 08:03 UTC, Schultzer commented on models/bug_report.js
> +  if (!this.created_at) {
Then we not following StandardJS

2016-11-29 08:03 UTC, Schultzer commented on models/crash_report.js
> +  if (!this.created_at) {
Then we not following StandardJS

2016-11-29 08:04 UTC, Schultzer commented on controllers/api_breakpad.js
> +    var writeStream
Then we not following StandardJS

2016-11-29 08:04 UTC, Schultzer commented on controllers/api_breakpad.js
> +      if (error) {
Then we not following StandardJS

2016-11-29 08:04 UTC, Schultzer commented on controllers/api_receipt.js
> +  var storage
Then we not following StandardJS

2016-11-29 08:04 UTC, Schultzer commented on controllers/api_receipt.js
> +    console.log(req.file.path)
Then we not following StandardJS

2016-11-29 08:05 UTC, Schultzer commented on controllers/auth_github.js
> +    var User
Variable User is not defined

2016-11-29 08:05 UTC, Schultzer commented on public/javascripts/receipt.js
> +      var location
Variable location is not defined

2016-11-30 01:09 UTC, danschultzer requested changes

2016-11-30 01:09 UTC, danschultzer commented on middlewares/api_auth.js
> +        if (!admin) {
This could probably be one-liner too.

2016-11-30 01:15 UTC, danschultzer requested changes

2016-11-30 01:15 UTC, danschultzer commented on controllers/auth_github.js
> +    Admin.findById(id, function (err, admin) { done(err, admin) })
The function should be in multiple lines.

2016-11-30 01:15 UTC, danschultzer commented on controllers/auth_github.js
> +  passport.serializeUser(function (admin, done) { done(null, admin._id) })
The function should be in multiple lines.

2016-11-30 01:15 UTC, danschultzer commented on helpers/send_report_to_admins.js
> +      emails = admins.map(function (admin) { return admin.email })
Multiline

2016-11-30 01:15 UTC, danschultzer commented on public/javascripts/receipt.js
> +                var alert = alert(error.message)
Why is this a var?

2016-11-30 01:50 UTC, danschultzer approved these changes

2016-11-30 01:52 UTC, merged